### ISSUE TITLE
zl sensor and hotend E4

### ISSUE THREAD

**Issue by Tekilero01** [ZONESTAR3D/Firmware#2]
the firmware used for the E4 hotend brings the option to change the type of hotend; mixing or not mixing, but this firmware doesn't work with ZL sensor. I wanted to know if there will be any update so that both the sensor and the hotend work

firmware hotend E4 2.0.0
firmware ZL sensonr 1.3.6

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,
        Please print and reply the new bracket for ZL-sensor.
    
        
            
        
    
    
     
    
        
                    HallyCTOShenZhen ZONSTAR INNV. Tech. Co., ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        8/5/2022 12:56
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [ZONESTAR3D/Firmware] zl sensor and hotend E4 (Issue #2)
        
      
    
  
  
the firmware used for the E4 hotend brings the option to change the type of hotend; mixing or not mixing, but this firmware doesn't work with ZL sensor. I wanted to know if there will be any update so that both the sensor and the hotend work
firmware hotend E4 2.0.0
firmware ZL sensonr 1.3.6

**Comment by ZONESTAR3D** [comment]
Please print and reply the new bracket for ZL-sensor.
